version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: refapp
    container_name: refapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:latest  # Use the desired MySQL version
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: refapp_db  # Your database name
      MYSQL_USER: user           # The new user to create
      MYSQL_PASSWORD: password   # The password for the new user
      MYSQL_ROOT_PASSWORD: rootpassword # Root password (use a secure one)
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
